# Generated by Django 5.2.9 on 2025-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_representative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
